### ISSUE TITLE
Процесс реконфигурирования и токен

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#15]
Процесс реконфигурирования должен заменять и токен, даже если он валидный. Смысл в том, что init — способ заменить конфигурацию, в том числе и если мы хотим перейти на другого пользователя. 

Однако, если у нас истек срок действия токена, то не надо думать, что пользователь захочет обновить и остальные параметры, скорее всего он захочет обновить только токен. 
Т.е. такого быть не должно:
```
[vvzvlad@MBP](03:31): python3 main.py init
Token expired!
Starting auth process..
After 6 seconds, the authentication site will open, do not close the tab after allowing access
Paste link to open page: https://oauth.vk.com/blank.html#access_token=...
Token is okay
Variables are ok. Do you want to reconfigure them? (Y/n): 

Configure variables:
```

Надо сделать так, чтобы init стирал все и конфигурировал заново, ничего не спрашиваю, а отдельный метод update_token — обновлял бы только токен.

**Comment by hazzus** [comment]
@vvzvlad то есть `'init'` в аргументах то идет предупреждение и все затирается? А если в аргументах `'update_token'` то обновляется токен?

**Comment by vvzvlad** [comment]
Да

**Comment by hazzus** [comment]
С трудом смержил твой pull с этим фиксом, но все в итоге вроде работает
