### ISSUE TITLE
[Low priority] Делать из номера пользователя его ник

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#17]
Если с помощью API можно несложно получить из номера пользователя текстовой ник пользователя(https://vk.com/vvzvlad), то стоит в консоль выводить их, нагляднее будет. Если это нетривиально, то некритично.

**Comment by vvzvlad** [comment]
Да, надо вызвать users.get с ID пользователя и запросить screen_name.
https://vk.com/dev/users.get

**Comment by hazzus** [comment]
Сделал, добавил даже имя)
