### ISSUE TITLE
[Medium priority] Режим "init" и "update token"

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#19]
Неправильно работает. "init" должен создавать, либо обнулять конфигурацию. Всю конфигурацию, включая токен. "update token" должен только обновлять токен. 

Т.е. в init надо добавить получение токена первичное, чтобы не запускать еще и "update token" при первой настройке

**Comment by hazzus** [comment]
Fixed? надеюсь..)
