### ISSUE TITLE
Изменить файл настроек и логику работы первого включения

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#2]
Сейчас файл настроек такого вида 
```
[~/Documents/Проекты/liker-group-script][master]
[vvzvlad@MBP](21:54): cat variables.log 
5
2.0
test_group
2
```

Не очень понятно, что за переменные, а для из изменения надо удалять файл заново, и запускать инициализацию. Хочется: 

1)Сделать человекочитаемый файл настроек, например JSON, чтобы было понятно, что там за параметры и поправить их ручками. Можно и ini-формат("delay=5"), но лучше JSON.
2)Сменить расширение на cfg, так как там не логи, а настройки
3)Сделать первую инициализацию не автоматической, а отдельной командой. Что-то вроде:
```

[~/Documents/Проекты/liker-group-script][master]
[vvzvlad@MBP](21:54): python3 main.py
Не могу начать работу: нет файла настроек, необходима первичная инициализация, выполните "main.py init"

[~/Documents/Проекты/liker-group-script][master]
[vvzvlad@MBP](21:58): python3 main.py init
[процесс логина и настройки]

[~/Documents/Проекты/liker-group-script][master]
[vvzvlad@MBP](21:58): python3 main.py
[нормальная работа]

[~/Documents/Проекты/liker-group-script][master]
[vvzvlad@MBP](21:58): python3 main.py init
Если вы продолжите, старый файл настроек будет удален после конца инициализации. 
[процесс логина и настройки]
```

Смысл в том, что не надо смешивать бизнес-логику и интерактивные конфигураторы. Нормальная работа скрипта — это запуск его без параметров, и в случае каких-либо проблем(например, поврежденный или отсутствующий файл конфигурации), он должен о них сказать и упасть, а не висеть вечно с вопросом "давайте начнем настройку". Потому что он может быть запущен не на пользовательском терминале, а супервизором, и консоли, а тем более ввода пользователя там может не быть вообще, только перенос сообщений из STDOUT/STDERROR в логи. А так получится, что де-юре, с точки зрения супервизора, скрипт штатно работает(не падает), а де-факто он функции не выполняет, потому что ждет ответа пользователя. 

Поэтому интерактивный конфигуратор — совершенно отдельная фича, которая крутая, но должна запускаться отдельной командой, в случае, если пользователь уверен, что он хочет запустить именно конфигуратор. 

Ну и с точки зрения разных уровней, хорошо, если старая конфигурация будет стираться инициализацией, а не удалением файла, это делает интерфейс взаимодействия с программой единым — с помощью команд, а не смешивает команды и действия с файловой системой.

**Comment by hazzus** [comment]
Конфиг файлы пофиксил, логику чуть позже

**Comment by hazzus** [comment]
done

**Comment by vvzvlad** [comment]
А какой смысл выносить конфигурацию в отдельный файл, если там только вызов кода из основного файла? Либо утащить в configure всю логику конфигурации, и сделать ее вообще независимой от остального кода, либо оставить ее в main, и запускать что-нибудь типа "main configure", без лишних файлов.

**Comment by hazzus** [comment]
Я думал об этом, но мне казалось что в отдельный файл проще, потому что иначе нужно подключать библиотеку связанную с аргументами командной строки и получится еще больше кода и зависимостей(хотя мб она встроенная). Можно сделать другую ветку))

**Comment by hazzus** [comment]
@vvzvlad можно форкнуть или сделать обе возможности

**Comment by vvzvlad** [comment]
Ой, все. Не можешь выбрать из двух вариантов — я выберу сам. 

Оставить конфигуратор в main, запускать не автоматически, а по аргументу "init", зависимость — не страшно. Вынести конфигуратор логически в отдельную функцию, не связанную с остальным кодом. Плодить форки и ветки без необходимости смысла нет, я хочу единую кодовую базу.

**Comment by hazzus** [comment]
Окей, я честно все сделал)
