### ISSUE TITLE
[High priority] Непонятное с количеством лайков

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#8]
На страничке один пост, в логах:
Лайкаю пост 20 пользователя 50789452
Лайкаю пост 20 пользователя 50789452
Лайкаю пост 20 пользователя 50789452
Лайкаю пост 20 пользователя 50789452

**Comment by vvzvlad** [comment]
Хм, вот тут что-то непонятное. Постов там несколько, но лайкает упорно один. На остальных пользователях все нормально.

> Post 4435 user https://vk.com/id125140834 has been liked.
> Post 4240 user https://vk.com/id125140834 has been liked.
> Post 3912 user https://vk.com/id125140834 has been liked.
> Post 3784 user https://vk.com/id125140834 has been liked.
> Post 3612 user https://vk.com/id125140834 has been liked.
> User http://vk.com/id125140834 posts were liked. Totally 347 users liked (41.56%)
> Post 3061 user https://vk.com/id126292373 has been liked.
> Post 3061 user https://vk.com/id126292373 has been liked.
> Post 3061 user https://vk.com/id126292373 has been liked.
> Post 3061 user https://vk.com/id126292373 has been liked.
> Post 3061 user https://vk.com/id126292373 has been liked.
> User http://vk.com/id126292373 posts were liked. Totally 348 users liked (41.68%)
> Post 1229 user https://vk.com/id126626154 has been liked.
> Post 1109 user https://vk.com/id126626154 has been liked.
> Post 1046 user https://vk.com/id126626154 has been liked.
> Post 1002 user https://vk.com/id126626154 has been liked.
> Post 938 user https://vk.com/id126626154 has been liked.

**Comment by hazzus** [comment]
Ахахаха, оч тупую багу нашел, жесть прям
inf режим просто тупо не должен был работать)
Я не смещал offset при получении постов. Вообще. Вот это да...

**Comment by hazzus** [comment]
Правда не знаю связано ли это с такой работой, но нашел пока думал почему так происходит

**Comment by hazzus** [comment]
Debug-mode говорит, что все хорошо и прекрасно, наверное пофикшено
