### ISSUE TITLE
Добавить информацию о ходе выполнения

### ISSUE THREAD

**Issue by vvzvlad** [hazzus/liker-group-script#9]
Добавить в get_information_from_file информацию о том, сколько уже лайкнуто, а в лог выполнения — о том, сколько человек из какого количества в группе обработано:

`Лайкаю пост 3882 пользователя 50959866 (230 из 858, 26% группы обработано)
`

`Запускаю продолжение процесса (обработано 230 пользователей)
`

**Comment by hazzus** [comment]
done
